"""Scope resolution on real git repositories: what is left out by default, what each filter keeps,
and the refusal a scope over its cap gets, with the counts a caller narrows from."""

from __future__ import annotations

from pathlib import Path

import pytest
from git_repos import commit_all, git, write_files

from jev_navigator.index.scope import (
    InvalidScopeError,
    ResolvedScope,
    Scope,
    ScopeRefusal,
    is_test_file,
    resolve_scope,
)

SOURCE = "def run():\n    return 1\n"
SCRIPT = "export function run() {\n  return 1;\n}\n"


def _repository(root: Path, files: dict[str, str]) -> Path:
    root.mkdir()
    write_files(root, files)
    commit_all(root)
    return root


def _scope(repo: Path, **fields: object) -> Scope:
    """A scope with the switches and cap a canonical request carries when it names none."""
    canonical = {
        "with_tests": False,
        "with_generated": False,
        "with_vendored": False,
        "with_docs": False,
        "max_files": 200,
    }
    return Scope(repo=repo, **(canonical | fields))


def _files(scope: Scope) -> tuple[str, ...]:
    resolved = resolve_scope(scope)
    assert isinstance(resolved, ResolvedScope)
    return resolved.files


@pytest.fixture
def mixed_repo(tmp_path: Path) -> Path:
    """Two source files beside one file of every kind the default scope leaves out."""
    return _repository(
        tmp_path / "repo",
        {
            "app/orders.py": SOURCE,
            "web/routes.ts": SCRIPT,
            "tests/test_orders.py": SOURCE,
            "app/orders_test.py": SOURCE,
            "web/routes.spec.ts": SCRIPT,
            "vendor/lib.py": SOURCE,
            "third_party/copied.py": SOURCE,
            "node_modules/pkg/index.js": SCRIPT,
            "gen/schema.py": "# Code generated by protoc. DO NOT EDIT.\n" + SOURCE,
            "gen/client.ts": "// @generated\n" + SCRIPT,
            "build/out.py": SOURCE,
            "lib/copied.py": SOURCE,
            ".gitattributes": "build/out.py linguist-generated\nlib/copied.py linguist-vendored\n",
            "docs/conf.py": SOURCE,
            "README.md": "# Repo\n",
            "guide.rst": "Guide\n=====\n",
        },
    )


def test_tests_generated_vendored_and_docs_are_left_out_by_default(mixed_repo: Path) -> None:
    assert _files(_scope(mixed_repo)) == ("app/orders.py", "web/routes.ts")


@pytest.mark.parametrize(
    ("flag", "brought_back"),
    [
        ("with_tests", {"tests/test_orders.py", "app/orders_test.py", "web/routes.spec.ts"}),
        ("with_generated", {"gen/schema.py", "gen/client.ts", "build/out.py"}),
        (
            "with_vendored",
            {"vendor/lib.py", "third_party/copied.py", "node_modules/pkg/index.js", "lib/copied.py"},
        ),
        ("with_docs", {"docs/conf.py", "README.md", "guide.rst"}),
    ],
)
def test_each_flag_brings_back_only_its_own_kind(mixed_repo: Path, flag: str, brought_back: set[str]) -> None:
    files = _files(_scope(mixed_repo, **{flag: True}))

    assert set(files) == {"app/orders.py", "web/routes.ts"} | brought_back


def test_only_files_jvn_parses_enter_the_scope(tmp_path: Path) -> None:
    repo = _repository(
        tmp_path / "repo",
        {"app/orders.py": SOURCE, "package.json": "{}\n", "logo.svg": "<svg/>\n", "Makefile": "all:\n"},
    )

    assert _files(_scope(repo)) == ("app/orders.py",)


def test_a_do_not_edit_header_marks_a_file_generated_but_a_late_mention_does_not(tmp_path: Path) -> None:
    late_mention = "".join(f"x{line} = {line}\n" for line in range(20)) + "# DO NOT EDIT the table above\n"
    repo = _repository(
        tmp_path / "repo",
        {"app/made.py": "# DO NOT EDIT: written by make\n" + SOURCE, "app/table.py": late_mention},
    )

    assert _files(_scope(repo)) == ("app/table.py",)
    assert _files(_scope(repo, with_generated=True)) == ("app/made.py", "app/table.py")


def test_a_do_not_edit_comment_in_any_case_marks_a_file_generated(tmp_path: Path) -> None:
    prisma_header = (
        "/* !!! This is code generated by Prisma. Do not edit directly. !!!\n/* eslint-disable */\n"
    )
    repo = _repository(
        tmp_path / "repo", {"app/orders.py": SOURCE, "prisma/client/index.js": prisma_header + SCRIPT}
    )

    assert _files(_scope(repo)) == ("app/orders.py",)


def test_do_not_edit_in_code_rather_than_a_comment_leaves_a_file_in_scope(tmp_path: Path) -> None:
    repo = _repository(
        tmp_path / "repo",
        {
            "app/form.py": 'HINT = "Do not edit this field"\n' + SOURCE,
            "app/lock.py": 'LOCK = "DO NOT EDIT"\n',
        },
    )

    assert _files(_scope(repo)) == ("app/form.py", "app/lock.py")


def test_a_false_linguist_attribute_keeps_a_file_the_path_rule_would_leave_out(tmp_path: Path) -> None:
    repo = _repository(
        tmp_path / "repo",
        {
            "vendor/ours.py": SOURCE,
            "vendor/theirs.py": SOURCE,
            ".gitattributes": "vendor/ours.py -linguist-vendored\n",
        },
    )

    assert _files(_scope(repo)) == ("vendor/ours.py",)


def test_language_filter_leaves_other_languages_out(mixed_repo: Path) -> None:
    assert _files(_scope(mixed_repo, languages=("python",))) == ("app/orders.py",)


@pytest.mark.parametrize(
    ("include", "exclude", "expected"),
    [
        (("app",), (), ("app/legacy/old.py", "app/orders.py")),
        (("app/orders.py",), (), ("app/orders.py",)),
        (("**/*.ts",), (), ("web/api/routes.ts",)),
        (("app/*",), (), ("app/orders.py",)),
        (("/*",), (), ("main.py",)),
        (("**/[n-p]*",), (), ("app/legacy/old.py", "app/orders.py", "lib/notes_draft.py")),
        ((), ("*_draft.py",), ("app/legacy/old.py", "app/orders.py", "main.py", "web/api/routes.ts")),
        ((), ("app/legacy/**",), ("app/orders.py", "lib/notes_draft.py", "main.py", "web/api/routes.ts")),
        ((), ("app",), ("lib/notes_draft.py", "main.py", "web/api/routes.ts")),
    ],
)
def test_folders_and_patterns_narrow_the_scope(
    tmp_path: Path, include: tuple[str, ...], exclude: tuple[str, ...], expected: tuple[str, ...]
) -> None:
    repo = _repository(
        tmp_path / "repo",
        {
            "app/orders.py": SOURCE,
            "app/legacy/old.py": SOURCE,
            "lib/notes_draft.py": SOURCE,
            "web/api/routes.ts": SCRIPT,
            "main.py": SOURCE,
        },
    )

    assert _files(_scope(repo, include=include, exclude=exclude)) == expected


def test_changed_since_limits_the_scope_to_changed_files(tmp_path: Path) -> None:
    repo = _repository(tmp_path / "repo", {"a.py": SOURCE, "b.py": SOURCE, "gone.py": SOURCE})
    base = git(repo, "rev-parse", "HEAD").strip()
    write_files(repo, {"b.py": SOURCE + "\n", "c.py": SOURCE})
    git(repo, "rm", "-q", "gone.py")
    git(repo, "add", ".")
    git(repo, "commit", "-qm", "change b, add c, remove gone")
    write_files(repo, {"untracked.py": SOURCE})

    resolved = resolve_scope(_scope(repo, changed_since=base))

    assert isinstance(resolved, ResolvedScope)
    assert resolved.files == ("b.py", "c.py", "untracked.py")
    assert resolved.filters["changed_since_commit"] == base


def test_the_resolved_scope_names_every_filter_it_applied(mixed_repo: Path) -> None:
    resolved = resolve_scope(_scope(mixed_repo, include=("app",), languages=("python",)))

    assert isinstance(resolved, ResolvedScope)
    assert resolved.filters == {
        "include": ["app"],
        "exclude": [],
        "languages": ["python"],
        "with_tests": False,
        "with_generated": False,
        "with_vendored": False,
        "with_docs": False,
        "changed_since": None,
        "changed_since_commit": None,
        "max_files": 200,
    }


@pytest.fixture
def wide_repo(tmp_path: Path) -> Path:
    """201 source files: 120 Python in pkg/api, 60 TypeScript in pkg/web, 21 Python directly in pkg."""
    files = {f"pkg/api/m{number}.py": SOURCE for number in range(120)}
    files |= {f"pkg/web/m{number}.ts": SCRIPT for number in range(60)}
    files |= {f"pkg/m{number}.py": SOURCE for number in range(21)}
    files["tests/test_ignored.py"] = SOURCE
    return _repository(tmp_path / "repo", files)


def test_scope_over_the_cap_is_refused(wide_repo: Path) -> None:
    refusal = resolve_scope(_scope(wide_repo))

    assert isinstance(refusal, ScopeRefusal)
    assert (refusal.files, refusal.cap) == (201, 200)
    assert refusal.filters["max_files"] == 200


def test_the_refusal_lists_file_counts_per_folder_and_language(wide_repo: Path) -> None:
    refusal = resolve_scope(_scope(wide_repo))

    assert isinstance(refusal, ScopeRefusal)
    assert refusal.counts_by_folder == {"pkg/api/": 120, "pkg/web/": 60, "/pkg/*": 21}
    assert refusal.counts_by_language == {"python": 141, "typescript": 60}


def test_each_folder_count_label_keeps_exactly_the_files_it_counts_under_the_same_filters(
    tmp_path: Path,
) -> None:
    repo = _repository(
        tmp_path / "repo",
        {
            "main.py": SOURCE,
            "setup.py": SOURCE,
            "src/a.py": SOURCE,
            "src/deep/b.py": SOURCE,
            "web/c.ts": SCRIPT,
            "src/test_a.py": SOURCE,
        },
    )
    refusal = resolve_scope(_scope(repo, max_files=4))
    assert isinstance(refusal, ScopeRefusal)

    included = {label: len(_files(_scope(repo, include=(label,)))) for label in refusal.counts_by_folder}

    assert refusal.counts_by_folder == {"/*": 2, "src/": 2, "web/": 1}
    assert included == refusal.counts_by_folder


def test_a_caller_may_raise_the_cap_to_exactly_the_files_in_scope(wide_repo: Path) -> None:
    resolved = resolve_scope(_scope(wide_repo, max_files=201))

    assert isinstance(resolved, ResolvedScope)
    assert len(resolved.files) == 201


@pytest.mark.parametrize("field", ["with_tests", "with_generated", "with_vendored", "with_docs", "max_files"])
def test_the_cap_and_switches_come_only_from_the_request(tmp_path: Path, field: str) -> None:
    fields = dict(vars(_scope(tmp_path)))
    del fields[field]

    with pytest.raises(TypeError, match=field):
        Scope(**fields)


@pytest.mark.parametrize(
    ("field", "value", "path"),
    [
        ("languages", ("cobol",), "/scope/languages"),
        ("changed_since", "no-such-ref", "/scope/changed_since"),
    ],
)
def test_an_unusable_scope_field_is_named(mixed_repo: Path, field: str, value: object, path: str) -> None:
    with pytest.raises(InvalidScopeError) as raised:
        resolve_scope(_scope(mixed_repo, **{field: value}))

    assert raised.value.path == path


def test_a_missing_repository_is_named(tmp_path: Path) -> None:
    with pytest.raises(InvalidScopeError) as raised:
        resolve_scope(_scope(tmp_path / "absent"))

    assert raised.value.path == "/scope/repo"


def test_changed_since_outside_git_is_named(tmp_path: Path) -> None:
    write_files(tmp_path, {"a.py": SOURCE})

    with pytest.raises(InvalidScopeError) as raised:
        resolve_scope(_scope(tmp_path, changed_since="HEAD"))

    assert raised.value.path == "/scope/changed_since"


def test_a_ref_that_looks_like_an_option_is_refused_without_running_it(
    mixed_repo: Path, tmp_path: Path
) -> None:
    written = tmp_path / "written-by-git"

    with pytest.raises(InvalidScopeError) as raised:
        resolve_scope(_scope(mixed_repo, changed_since=f"--output={written}"))

    assert raised.value.path == "/scope/changed_since"
    assert not written.exists()


def test_a_ref_whose_name_begins_with_a_dash_is_read_as_a_name(mixed_repo: Path) -> None:
    git(mixed_repo, "update-ref", "refs/tags/-v1", "HEAD")

    resolved = resolve_scope(_scope(mixed_repo, changed_since="-v1"))

    assert isinstance(resolved, ResolvedScope)
    assert resolved.filters["changed_since_commit"] == git(mixed_repo, "rev-parse", "HEAD").strip()


def test_a_directory_outside_git_is_listed_by_ripgrep(tmp_path: Path) -> None:
    write_files(tmp_path, {"a.py": SOURCE, "tests/test_a.py": SOURCE})

    assert _files(_scope(tmp_path)) == ("a.py",)


@pytest.mark.parametrize(
    "path",
    [
        "tests/orders.py",
        "app/test/orders.py",
        "web/__tests__/routes.ts",
        "spec/routes.js",
        "app/test_orders.py",
        "app/orders_test.py",
        "web/routes.test.ts",
        "web/routes.spec.tsx",
        "conftest.py",
        "app/conftest.py",
    ],
)
def test_a_test_folder_or_test_file_name_marks_a_test_file(path: str) -> None:
    assert is_test_file(path)


@pytest.mark.parametrize(
    "path",
    [
        "app/latest.py",
        "app/contest.py",
        "testing/helpers.py",
        "app/testdata.py",
        "app/attest_test_helpers/orders.py",
        "web/inspect.ts",
        "tests.py",
    ],
)
def test_a_name_that_only_contains_test_is_not_a_test_file(path: str) -> None:
    assert not is_test_file(path)
